CREATE TABLE `award_winners` (
  `key_id` int NOT NULL,
  `tournament_id` varchar(25) DEFAULT NULL,
  `tournament_name` varchar(50) DEFAULT NULL,
  `award_id` varchar(10) DEFAULT NULL,
  `award_name` varchar(25) DEFAULT NULL,
  `shared` tinyint(1) DEFAULT NULL,
  `player_id` varchar(40) DEFAULT NULL,
  `family_name` varchar(25) DEFAULT NULL,
  `given_name` varchar(25) DEFAULT NULL,
  `team_id` varchar(15) DEFAULT NULL,
  `team_name` varchar(25) DEFAULT NULL,
  `team_code` varchar(15) DEFAULT NULL,
  PRIMARY KEY (`key_id`),
  UNIQUE KEY `key_id` (`key_id`),
  KEY `tournament_id` (`tournament_id`),
  KEY `award_id` (`award_id`),
  KEY `player_id` (`player_id`),
  KEY `team_id` (`team_id`),
  CONSTRAINT `award_winners_ibfk_1` FOREIGN KEY (`tournament_id`) REFERENCES `tournaments` (`tournament_id`),
  CONSTRAINT `award_winners_ibfk_2` FOREIGN KEY (`award_id`) REFERENCES `awards` (`award_id`),
  CONSTRAINT `award_winners_ibfk_3` FOREIGN KEY (`player_id`) REFERENCES `players` (`player_id`),
  CONSTRAINT `award_winners_ibfk_4` FOREIGN KEY (`team_id`) REFERENCES `teams` (`team_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci